# Generated by Django 4.1.3 on 2022-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=254)),
                ('desc', models.TextField()),
                ('pdf', models.FileField(upload_to=None)),
                ('freq', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
