# Generated by Django 4.1.3 on 2022-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prints',
            name='spiral',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
