# Generated by Django 4.1.3 on 2022-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prints_spiral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prints',
            name='spiral',
            field=models.BooleanField(),
        ),
    ]
